service: aws-node-http-api-project
frameworkVersion: '3'

params: #environment variables
  default:
    dbName: servless
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: PJH1KgDkTYhAhpFW2D8YVIS2hs8vg3sV

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DB_CONNECTION_STRING: ${param:connectionString}
    MONGO_DB_NAME: ${param:dbName}
    SALT: ${param:salt}

functions:
  sendResponse:
    handler: api/handler.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
                application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/handler.getResult
    events:
      - httpApi:
          path: /api/results/{id}
          method: get
plugins:
  - serverless-offline
